# NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

In [4]:
import numpy as np

In [5]:
my_list = [1,2,3]
one_darray = np.array(my_list)

In [6]:
print(one_darray)

[1 2 3]


In [7]:
type(one_darray)

numpy.ndarray

In [8]:
one_darray

array([1, 2, 3])

In [9]:
print(one_darray.dtype)

int64


In [10]:
print(one_darray.shape)

(3,)


In [11]:
my_matrix = [[1,2],[4,5],[7,8]]
two_darray = np.array(my_matrix)
print(two_darray)


print(two_darray.dtype,"\n")
print(two_darray.shape)

[[1 2]
 [4 5]
 [7 8]]
int64 

(3, 2)


In [12]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

This is one dimension array and we Can aslso specify the type of data in the dtype argument:

In [13]:
a=np.array([1.4,2,3,4.8,5.1],dtype=float)
a

array([1.4, 2. , 3. , 4.8, 5.1])

There are two more methods to create an array as arrange() which arrange values by steps and linspace which divides the range in given parts in equal ratio

In [14]:
np.arange(0,10,2) # this is one dimensional range array and parameters are( start, stop, step)

array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0,10,5) #It will  divide into parts (start, stop, parts)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**Multidimensional NumPy Arrays**

In [16]:
np.array([[1,2,3,4],[5,6,7,8]]) #2D array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
p=np.array([[1,2,3,4],[5,6,7,8]],dtype=float)
p

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [21]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**Array Manipulation**

**Adding or Removing Elements**

In [84]:
a

array([1, 2, 3])

In [83]:
np.append(a,2)

array([1, 2, 3, 2])

## Random

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [26]:
np.random.randint(1,100)

12

In [27]:
y=np.random.randint(1,100,10)
y

array([38, 23,  9, 78,  1, 48, 55, 31, 75, 91])

In [28]:
x = np.random.randint(2,100,9)
print(x)

[10 33 65 52 73 15 81 12 31]


The np.random.random() function in NumPy generates random values from a uniform distribution over the interval [0, 1). This means that the values it produces will always be in the range [0, 1), where 0 is inclusive and 1 is exclusive. In other words, the random values will be greater than or equal to 0, but strictly less than 1

In [85]:
np.random.random((4,3))

array([[0.58894595, 0.88791981, 0.9349247 ],
       [0.12349965, 0.34393971, 0.68957092],
       [0.79624854, 0.2980964 , 0.70722161],
       [0.8364095 , 0.64289876, 0.87411705]])

In [86]:
np.random.random((3,3))  #Creates random array

array([[0.89557352, 0.31290146, 0.67724827],
       [0.07231153, 0.13427752, 0.32537533],
       [0.42840086, 0.79602134, 0.39154749]])

In [87]:
a = np.empty((2,2),dtype=int)    #Creates an empty array
a

array([[0, 1],
       [2, 3]])

In [88]:
np.eye((6),dtype = int)       #diagonal matrix

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [89]:
np.eye(6,k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [90]:
np.eye(6,k=-2)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

Properties

In [91]:
a= np.array ([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [92]:
a.shape

(2, 4)

In [93]:
len(a)

2

In [94]:
a.ndim

2

In [95]:
a.dtype

dtype('int64')

In [96]:
a.astype(type)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=object)

In [97]:
type(a)

numpy.ndarray

## Reshape
Returns an array containing the same data with a new shape.

In [29]:
x.reshape(3,3)

array([[10, 33, 65],
       [52, 73, 15],
       [81, 12, 31]])

In [30]:
y.reshape(2,5)

array([[38, 23,  9, 78,  1],
       [48, 55, 31, 75, 91]])

## Array Manipulation

#### Adding or Removing Elements

In [99]:
np.append(a,2)

array([1, 2, 3, 4, 5, 6, 7, 8, 2])

In [100]:
a=np.array([[1,2,3,4],[6,4,5,8]])
b=np.array([[7,8,9,2],[6,9,0,9]])
np.append(a,b)

array([1, 2, 3, 4, 6, 4, 5, 8, 7, 8, 9, 2, 6, 9, 0, 9])

In [101]:
np.insert(a, 1, 3, 0)   #Insert items into array at axis 0 or 1

array([[1, 2, 3, 4],
       [3, 3, 3, 3],
       [6, 4, 5, 8]])

In [102]:
np.insert(a, 1, 3, 1)

array([[1, 3, 2, 3, 4],
       [6, 3, 4, 5, 8]])

In [103]:
np.resize(a,(2,3))

array([[1, 2, 3],
       [4, 6, 4]])

In [104]:
np.delete(a,1,0)

array([[1, 2, 3, 4]])

### Reshaping NumPy Arrays

In [105]:
a = np.array([3,6,9,12,23,55])

np.reshape(a,(2,3))# reshaped the ndarray from a 1-D to a 2-D ndarray.

array([[ 3,  6,  9],
       [12, 23, 55]])

In [106]:
a = np.array([3,6,9,12,18,24])
print('Three rows :','\n',np.reshape(a,(3,2)))

Three rows : 
 [[ 3  6]
 [ 9 12]
 [18 24]]


### Combining Arrays

In [107]:
x=np.array([[1,2,3],[10,20,30]])
y=np.array([[11,12,13],[60,40,20]])
np.concatenate((x,y),axis=1)


array([[ 1,  2,  3, 11, 12, 13],
       [10, 20, 30, 60, 40, 20]])

In [108]:
np.vstack((x,y))

array([[ 1,  2,  3],
       [10, 20, 30],
       [11, 12, 13],
       [60, 40, 20]])

### Splitting of Arrays


In [109]:
np.array_split(x, 3)

[array([[1, 2, 3]]),
 array([[10, 20, 30]]),
 array([], shape=(0, 3), dtype=int64)]

In [110]:
np.hsplit(a, 2)

[array([3, 6, 9]), array([12, 18, 24])]

In [111]:
p= a.flatten()

In [112]:
p

array([ 3,  6,  9, 12, 18, 24])

In [113]:
x = np.transpose(p)
x.T

array([ 3,  6,  9, 12, 18, 24])

In [114]:
new=np.array([[2,2],[1,2]])

inverse = np.linalg.inv(new)
inverse

array([[ 1. , -1. ],
       [-0.5,  1. ]])

### Array Operations

In [115]:
x=np.array([[1,2,3],[10,20,30]])
y=np.array([[11,12,13],[60,40,20]])

z=x+y
z

array([[12, 14, 16],
       [70, 60, 50]])

In [116]:
np.add(x,y)

array([[12, 14, 16],
       [70, 60, 50]])

In [117]:
np.subtract(x,y)

array([[-10, -10, -10],
       [-50, -20,  10]])

In [118]:
np.divide(x,y)
#x/y

array([[0.09090909, 0.16666667, 0.23076923],
       [0.16666667, 0.5       , 1.5       ]])

In [119]:
np.multiply(x,y)
#x * y

array([[ 11,  24,  39],
       [600, 800, 600]])

In [120]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [3.16227766, 4.47213595, 5.47722558]])

In [121]:
np.sin(x)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.54402111,  0.91294525, -0.98803162]])

In [122]:
np.cos(x)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.83907153,  0.40808206,  0.15425145]])

In [123]:
np.log(x)

array([[0.        , 0.69314718, 1.09861229],
       [2.30258509, 2.99573227, 3.40119738]])

In [124]:
x1=np.array([[1,2],[10,20]])
y1=np.array([[11,12],[60,40]])


np.dot(x1,y1)

array([[ 131,   92],
       [1310,  920]])

In [125]:
np.roots([1,0,-4])

array([-2.,  2.])

### Basic Statistics

In [126]:
np.mean(x)

11.0

In [127]:
np.median(x)

6.5

In [128]:
np.std(x)

10.708252269472673

## Indexing and Slicing of NumPy array

In [136]:
a = np.array([1,2,3,4,5,6])
print(a[1:5:2])     #(start, end, step)

[2 4]


In [137]:
print(a[:6:2])
print(a[1::2])
print(a[1:6:])

[1 3 5]
[2 4 6]
[2 3 4 5 6]


In [138]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0,0])
print(a[1,2])
print(a[1,0])

1
6
4


### slicing

In [139]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
# print first row values
print(a ,'\n')

print(a[1:3,1:3])  # it prints value of 2nd and 3rd places from the 2nd and 3rd matrix which is at 1 and 2 places in indexing

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[5 6]
 [8 9]]


In [140]:
print(a[:,1:])

[[2 3]
 [5 6]
 [8 9]]


In [141]:
print(a[0:1,1:3])

[[2 3]]


In [142]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a,'\n')

print(a[:,-4], '\n')

print(a[1,-3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

[2 7] 

8


### Negative Slicing

In [143]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Original array :','\n',a)
print('Reversed array :','\n',a[::-1,::-1])

Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reversed array : 
 [[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [144]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Original array :','\n',a)
print('Slicing :','\n',a[::,::2])

Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Slicing : 
 [[ 1  3  5]
 [ 6  8 10]]


In [145]:
print('Reversed array vertically :','\n',np.flip(a,axis=1))
print('Reversed array horizontally :','\n',np.flip(a,axis=0))

Reversed array vertically : 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]
Reversed array horizontally : 
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


### Stacking and Concatenating

In [146]:
a = np.arange(0,5)
b = np.arange(5,10)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Vertical stacking :','\n',np.vstack((a,b)))
print('Horizontal stacking :','\n',np.hstack((a,b)))

Array 1 : 
 [0 1 2 3 4]
Array 2 : 
 [5 6 7 8 9]
Vertical stacking : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Horizontal stacking : 
 [0 1 2 3 4 5 6 7 8 9]


### Copying Arrays

There are 3 types of copying arrays

1. Aliasing

In [147]:
arr1= np.array([2,4,6,8])
arr2=arr1
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2)) # in this type of copying array we copied one array to other but both arrays are same there is no difference in both arrays

[2 4 6 8]
[2 4 6 8]
140398232775984
140398232775984


2. Shallow Copy

In [151]:
arr1= np.array([2,4,6,8])
arr2=arr1.view()
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
# in shallow copy we copy the element but both arrays are still dependent on each other that is if we update original one then there is change in copied array

[2 4 6 8]
[2 4 6 8]
140398232779152
140398232778384


In [152]:
arr1[1]=7

In [153]:
print(arr1)

[2 7 6 8]


In [154]:
print(arr2)

[2 7 6 8]


In [155]:
arr2[0]=9

In [156]:
print(arr2)

[9 7 6 8]


In [157]:
print(arr1)

[9 7 6 8]


3. Deep Copy

In [158]:
arr1= np.array([11,12,13,14,15])
arr2=arr1.copy()
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
# in deep copy there are completely two different arrays form by copying one array .

[11 12 13 14 15]
[11 12 13 14 15]
140398232780496
140398232895536


In [159]:
arr1[0]=10

In [160]:
print(arr1)

[10 12 13 14 15]


In [161]:
print(arr2)

[11 12 13 14 15]


#### Searching in Array

In [162]:
# Searching using where

a1 = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(a1 == 4)

print(x)

(array([3, 5, 6]),)


#### Filtering in Arrays

In [163]:
# filter
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


### Iterating over Array

In [164]:
a1 = np.array([1, 2, 3])

for i in a1:
    print(i)

1
2
3


In [167]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])

for i in a2:
  for j in i:
    print(j)

1
2
3
4
5
6


In [168]:
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in a3:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [169]:
#Creating sample array
arr = np.arange(1,11)

In [170]:
#Show
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [171]:
arr[8]

9

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [172]:
#Get a value at an index
arr[8]

9

In [173]:
#Get values in a range
arr[0:5]

array([1, 2, 3, 4, 5])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [174]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

In [175]:
#Show
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [176]:
#Setting a value with index range (Broadcasting)
array2 = np.arange(1,11)
array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [177]:
array2[0:5]=100
array2

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [178]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

# Add arrays 'a' and 'b'
result = a + b

print(result)


[[11 22 33]
 [14 25 36]]


## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [179]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [180]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [181]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [182]:
arr2d = np.ones((10,10))

In [183]:
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [184]:
#Set up array

for i in range(10):
    arr2d[i]= i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [185]:
import numpy as np
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [186]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [187]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [188]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [189]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [190]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [191]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

<ipython-input-191-2f119c028196>:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [192]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [193]:
import numpy as np

# Create a 1D array with numbers from 1 to 9
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape the array to a 3x3 matrix
reshaped_arr = arr.reshape(3, 3)

print("Original array:")
print(arr)
print()

print("Reshaped array:")
print(reshaped_arr)


Original array:
[1 2 3 4 5 6 7 8 9]

Reshaped array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [194]:
import numpy as np

# Create a 1D array with numbers from 1 to 9
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Reshape the array to a 3x3 matrix
reshaped_arr = arr.reshape(4, 2)

print("Original array:")
print(arr)
print()

print("Reshaped array:")
print(reshaped_arr)


Original array:
[1 2 3 4 5 6 7 8]

Reshaped array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# **Details on Datatypes**


**Datatypes in Python**

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j


**Datatypes in Numpy**


Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

In [195]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [196]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [197]:
# Create an array with data type string:

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [198]:
# For i, u, f, S and U we can define size as well.
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [199]:
arr = np.array([1.0 + 2.0j, 1.5 + 2.5j])
print(arr.dtype)

complex128


In [200]:
arr = np.array([-1, 2, 3], dtype='u2')
print(arr)

[65535     2     3]


In [201]:
# error if conversion not possible

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: ignored

In [202]:
# type conversion
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


**NumPy Array Copy vs View**

In [203]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [204]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [205]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


**Joining NumPy Arrays**

In [206]:
# 1D join
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [207]:
#2d Join
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)



[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [208]:
a= {1,2,3,4,5}
print(a)
type(a)


{1, 2, 3, 4, 5}


set

In [209]:
# stack
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack arrays 'a' and 'b' along a new axis
result = np.stack((a, b))

print(result)


[[1 2 3]
 [4 5 6]]


In [210]:
# hstack
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Horizontally stack arrays 'a' and 'b'
result = np.hstack((a, b))

print(result)


[1 2 3 4 5 6]


In [211]:
#vstack
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertically stack arrays 'a' and 'b'
result = np.vstack((a, b))

print(result)


[[1 2 3]
 [4 5 6]]


In [212]:
#dstack

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Depth-wise stack arrays 'a' and 'b'
result = np.dstack((a, b))

print(result)


[[[1 4]
  [2 5]
  [3 6]]]


**Split , Search, Sort, Filter**

In [213]:
# Split

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [214]:
# Searching using where

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [215]:
# Sorting
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [216]:
# filter
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
