## NumPy

NumPy is a Python package providing fast, flexible, and expressive data structures designed to make working with 'relationa' or 'labeled' data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python. It stands for 'Numerical Python'. 

## Creating a NumPy Array

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

This is one dimension array and we Can aslso specify the type of data in the dtype argument:

In [3]:
a=np.array([1.4,2,3,4.8,5.1],dtype=int)
a

array([1, 2, 3, 4, 5])

There are two more methods to create an array as arrange() which arrange values by steps and linspace which divides the range in given parts in equal ratio

In [4]:
np.arange(0,10,2) # this is one dimensional range array and parameters are( start, stop, step)

array([0, 2, 4, 6, 8])

In [5]:
np.linspace(0,10,5) # (start, stop, parts)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Multidimensional NumPy arrays 

In [6]:
np.array([[1,2,3,4],[5,6,7,8]]) #2D array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
p=np.array([[1,2,3,4],[5,6,7,8]])
p

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
np.zeros((5,5))	#creates two dim array with all elements as zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((5,5)) #creates two dim array with all elements as one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.random.random((3,3))  #Creates random array

array([[0.63440488, 0.71581752, 0.62523456],
       [0.63578152, 0.15643063, 0.45121319],
       [0.75936054, 0.56147942, 0.31544384]])

In [11]:
np.empty((2,2))    #Creates an empty array

array([[2.12199579e-314, 0.00000000e+000],
       [5.23709585e-321, 1.98491423e+070]])

In [12]:
np.eye(6)       #diagonal matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [13]:
np.eye(6,k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.eye(6,k=-2)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

Properties

In [15]:
a= np.array ([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
a.shape

(2, 4)

In [17]:
len(a)

2

In [18]:
a.ndim

2

In [19]:
a.dtype

dtype('int32')

In [20]:
a.astype(type)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=object)

In [21]:
type(a)

numpy.ndarray

In [26]:
#Setting a value with index range (Broadcasting)
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

## Array Manipulation

#### Adding or Removing Elements

In [23]:
np.append(a,2)

array([1, 2, 3, 4, 5, 6, 7, 8, 2])

In [37]:
a=np.array([[1,2,3,4],[6,4,5,8]])
b=np.array([[7,8,9,2],[6,9,0,9]])
np.append(a,b)

array([1, 2, 3, 4, 6, 4, 5, 8, 7, 8, 9, 2, 6, 9, 0, 9])

In [38]:
np.insert(a, 1, 3, 0)   #Insert items into array at axis 0 or 1

array([[1, 2, 3, 4],
       [3, 3, 3, 3],
       [6, 4, 5, 8]])

In [39]:
np.insert(a, 1, 3, 1)

array([[1, 3, 2, 3, 4],
       [6, 3, 4, 5, 8]])

In [40]:
np.resize(a,(2,3))

array([[1, 2, 3],
       [4, 6, 4]])

In [41]:
np.delete(a,1,0)

array([[1, 2, 3, 4]])

### Reshaping NumPy Arrays

In [42]:
a = np.array([3,6,9,12,23,55])

np.reshape(a,(2,3))# reshaped the ndarray from a 1-D to a 2-D ndarray.

array([[ 3,  6,  9],
       [12, 23, 55]])

In [43]:
a = np.array([3,6,9,12,18,24])
print('Three rows :','\n',np.reshape(a,(3,2)))

Three rows : 
 [[ 3  6]
 [ 9 12]
 [18 24]]


### Combining Arrays

In [44]:
x=np.array([[1,2,3],[10,20,30]])
y=np.array([[11,12,13],[60,40,20]])
np.concatenate((x,y),axis=1)


array([[ 1,  2,  3, 11, 12, 13],
       [10, 20, 30, 60, 40, 20]])

In [45]:
np.vstack((x,y))

array([[ 1,  2,  3],
       [10, 20, 30],
       [11, 12, 13],
       [60, 40, 20]])

### Splitting of Arrays


In [46]:
np.array_split(x, 3)

[array([[1, 2, 3]]),
 array([[10, 20, 30]]),
 array([], shape=(0, 3), dtype=int32)]

In [47]:
np.hsplit(a, 2)

[array([3, 6, 9]), array([12, 18, 24])]

In [48]:
p= a.flatten()

In [49]:
p

array([ 3,  6,  9, 12, 18, 24])

In [50]:
x = np.transpose(p)
x.T

array([ 3,  6,  9, 12, 18, 24])

In [51]:
new=np.array([[2,2],[1,2]])

inverse = np.linalg.inv(new)
inverse

array([[ 1. , -1. ],
       [-0.5,  1. ]])

### Array Operations

In [52]:
x=np.array([[1,2,3],[10,20,30]])
y=np.array([[11,12,13],[60,40,20]])

z=x+y
z

array([[12, 14, 16],
       [70, 60, 50]])

In [53]:
np.add(x,y)

array([[12, 14, 16],
       [70, 60, 50]])

In [54]:
np.subtract(x,y)

array([[-10, -10, -10],
       [-50, -20,  10]])

In [55]:
np.divide(x,y)
#x/y

array([[0.09090909, 0.16666667, 0.23076923],
       [0.16666667, 0.5       , 1.5       ]])

In [56]:
np.multiply(x,y)
#x * y

array([[ 11,  24,  39],
       [600, 800, 600]])

In [57]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [3.16227766, 4.47213595, 5.47722558]])

In [58]:
np.sin(x)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.54402111,  0.91294525, -0.98803162]])

In [59]:
np.cos(x)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.83907153,  0.40808206,  0.15425145]])

In [60]:
np.log(x)

array([[0.        , 0.69314718, 1.09861229],
       [2.30258509, 2.99573227, 3.40119738]])

In [61]:
x1=np.array([[1,2],[10,20]])
y1=np.array([[11,12],[60,40]])


np.dot(x1,y1)

array([[ 131,   92],
       [1310,  920]])

In [62]:
np.roots([1,0,-4])

array([ 2., -2.])

### Basic Statistics

In [63]:
np.mean(x)

11.0

In [64]:
np.median(x)

6.5

In [65]:
np.std(x)

10.708252269472673

## Indexing and Slicing of NumPy array

In [66]:
a = np.array([1,2,3,4,5,6])
print(a[1:5:2])     #(start, end, step)

[2 4]


In [67]:
print(a[:6:2])
print(a[1::2])
print(a[1:6:])

[1 3 5]
[2 4 6]
[2 3 4 5 6]


In [68]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0,0])
print(a[1,2])
print(a[1,0])

1
6
4


### slicing

In [69]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
# print first row values
print(a ,'\n')

print(a[1:3,1:3])  # it prints value of 2nd and 3rd places from the 2nd and 3rd matrix which is at 1 and 2 places in indexing

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[5 6]
 [8 9]]


In [70]:
print(a[:,1:])

[[2 3]
 [5 6]
 [8 9]]


In [71]:
print(a[0:1,1:3])

[[2 3]]


In [72]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a,'\n')

print(a[:,-4], '\n')

print(a[1,-3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

[2 7] 

8


### Negative Slicing

In [73]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Original array :','\n',a)
print('Reversed array :','\n',a[::-1,::-1])

Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reversed array : 
 [[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [74]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Original array :','\n',a)
print('Slicing :','\n',a[::,::2])

Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Slicing : 
 [[ 1  3  5]
 [ 6  8 10]]


In [75]:
print('Reversed array vertically :','\n',np.flip(a,axis=1))
print('Reversed array horizontally :','\n',np.flip(a,axis=0))

Reversed array vertically : 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]
Reversed array horizontally : 
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


### Stacking and Concatenating

In [76]:
a = np.arange(0,5)
b = np.arange(5,10)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Vertical stacking :','\n',np.vstack((a,b)))
print('Horizontal stacking :','\n',np.hstack((a,b)))

Array 1 : 
 [0 1 2 3 4]
Array 2 : 
 [5 6 7 8 9]
Vertical stacking : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Horizontal stacking : 
 [0 1 2 3 4 5 6 7 8 9]


### Copying Arrays

There are 3 types of copying arrays

1. Aliasing

In [77]:
arr1= np.array([2,4,6,8])
arr2=arr1
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2)) # in this type of copying array we copied one array to other but both arrays are same there is no difference in both arrays

[2 4 6 8]
[2 4 6 8]
2438961601488
2438961601488


2. Shallow Copy

In [78]:
arr1= np.array([2,4,6,8])
arr2=arr1.view()
print(arr1
print(arr2)
print(id(arr1))
print(id(arr2))
# in shallow copy we copy the element but both arrays are still dependent on each other that is if we update original one then there is change in copied array

[2 4 6 8]
[2 4 6 8]
2438961542128
2438961845424


In [87]:
arr1[1]=7

In [88]:
print(arr1)

[2 7 6 8]


In [89]:
print(arr2)

[2 7 6 8]


In [90]:
arr2[0]=9

In [91]:
print(arr2)

[9 7 6 8]


In [93]:
print(arr1)

[9 7 6 8]


3. Deep Copy

In [94]:
arr1= np.array([11,12,13,14,15])
arr2=arr1.copy()
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2)) 
# in deep copy there are completely two different arrays form by copying one array . 

[11 12 13 14 15]
[11 12 13 14 15]
2438961897168
2438961996976


In [95]:
arr1[0]=10

In [96]:
print(arr1)

[10 12 13 14 15]


In [97]:
print(arr2)

[11 12 13 14 15]


#### Searching in Array

In [101]:
# Searching using where

a1 = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(a1 == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


#### Filtering in Arrays

In [102]:
# filter
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


### Iterating over Array

In [106]:
a1 = np.array([1, 2, 3])

for i in a1:
    print(i)

1
2
3


In [110]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])

for i in a2:
    for j in i:
    print(j)

1
2
3
4
5
6


In [111]:
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in a3:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
