# Numpy - Excercise

What is Numpy?

Numpy is python package. It is used for working with arrays.

NumPy is short for "Numerical Python".

NumPy was created in 2005 by Travis Oliphant

## Advantages of Numpy:


Advantages of using NumPy for data analysis.

NumPy performs array-oriented computing.

It efficiently implements the multidimensional arrays.
It performs scientific computations.

NumPy provides the in-built functions for linear algebra and random number generation.

### Importing the numpy library

In [1]:
import numpy as np

In [2]:
# NumPy version

print(np.__version__)
#print(np.show_config())

1.20.3


### Creating Arrays

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
#Use a tuple to create a NumPy array:

import numpy as np

arrt = np.array((1, 2, 3, 4, 5))

print(arrt)

[1 2 3 4 5]


In [3]:
# Using Arange()

arr11=np.arange(1,10,2)
print(arr11)

[1 3 5 7 9]


In [6]:
# Array with 0s:
arr0=np.zeros(2,dtype='int')  # np.zeros[shape=2,dtype] here shape is no of zeros
arr0 

array([0, 0])

In [7]:
# Arrays with 1s:
arr1s=np.ones(3,int)
arr1s

array([1, 1, 1])

In [8]:
# numpy.eye
#The eye tool returns a 2-D array with  1’s as the diagonal and  0’s elsewhere.
arrA= np.eye(4, 4, k = 0, dtype='int') # k=0 means main diagonal, k=1 means diagonal above main and k=-1 below main diagonal
print(arrA)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


### Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.

### 0-D Arrays:

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [9]:
arr1=np.array(14)
print(arr1)

14


### 1-D Arrays:
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [10]:
import numpy as np

arr2 = np.array([1, 2, 3, 4, 5])

print(arr2)

[1 2 3 4 5]


### 2-D Arrays:
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [11]:
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [12]:
arr4=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr4)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Dimension of Arrays: 
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [13]:
print(arr1.ndim)

0


In [14]:
print(arr2.ndim)

1


In [15]:
print(arr3.ndim)

2


In [16]:
print(arr4.ndim)

3


### Higher Dimensional Arrays:
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [17]:
import numpy as np
arr5=np.array([1,2,3,4], ndmin=5)
print(arr5)
print("No of Dimensions:", arr5.ndim)

## Here, "ndmin" is used to assign number of dimensions as an argument.

[[[[[1 2 3 4]]]]]
No of Dimensions: 5


## Array Indexing:
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [4]:
arr6=np.array([1,2,3,4])
print(arr6[3])            # Accessing the element at index 3

4


In [5]:
print(arr6[1],arr6[3])   # Accessing the elements at index 1 and 3
print(arr6[1]+arr6[3])   # And adding them

2 4
6


In [20]:
### Accessing 2_D Arrays
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)
print("2nd element at 1st row is:",arr3[0,1])

[[1 2 3]
 [4 5 6]]
2nd element at 1st row is: 2


In [21]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])   

5th element on 2nd row:  10


In [22]:
### Access 3-D Arrays
print(arr4)
print("The 3rd element in 2nd Array in 1st Array is", arr4[0,1,2])

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
The 3rd element in 2nd Array in 1st Array is 6


### Negative Indexing:
To access the element from end of a array.

In [23]:
print(arr)
print("Element at index -1 is:",arr[-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Element at index -1 is: [ 6  7  8  9 10]


In [24]:
print("Element at index -2 is:", arr[-2])

Element at index -2 is: [1 2 3 4 5]


### Array Slicing: 
Slicing in python means taking elements from one given index to another given index.

In [25]:
arr=[1,2,3,4,5,6,7]
print(arr)

[1, 2, 3, 4, 5, 6, 7]


In [26]:
print(arr[2:6])   # Slicing elements from index 2 to 6

[3, 4, 5, 6]


In [27]:
print(arr[4:])   # Slicing elements from index 4th to end

[5, 6, 7]


In [28]:
print(arr[:4])  # Slicing elements from start to index 4th (not included 4th index element)

[1, 2, 3, 4]


In [29]:
print(arr[:])   # No Slicing

[1, 2, 3, 4, 5, 6, 7]


### Negative Slicing

In [30]:
print(arr[-3:-1])  # Slicing from "END" from index 3 to 1

[5, 6]


In [31]:
print(arr[:-3])   #Slicing till index 3

[1, 2, 3, 4]


### Step Slicing:

In [32]:
print(arr[1:6:2])  # Slicing from index 1 to 6 with gap of 2  
                   #(arr[start: end: step value])

[2, 4, 6]


In [33]:
print(arr[::2])    # Slicing every other element from start to end.

[1, 3, 5, 7]


## Slicing 2-D Arrays:

In [34]:
arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [35]:
print(arr3[1,1:4])  # Slicing element from index 1 to 4(not included) from 2nd row i.e 2nd element in 2-D array  (row=element)

[7 8 9]


In [36]:
#From both elements, return index 2:
print(arr3[0:1,3])  # Slicing element from both elements(rows) at index 3rd

[4]


In [37]:
print(arr3[0:1,1:4])  # Slicing element from both elements(rows) from index 1 to 4 (not included)

[[2 3 4]]


## Operations on Arrays:

In [38]:
import numpy as np


# Initializing the array
arrOP1 = np.arange(4, dtype = 'int').reshape(2, 2)

print('First array:')
print(arrOP1)

print('\nSecond array:')
arrOP2 = np.array([12, 12])
print(arrOP2)

print('\nAdding the two arrays:')
print(np.add(arrOP1, arrOP2))

print('\nSubtracting the two arrays:')
print(np.subtract(arrOP1, arrOP2))

print('\nMultiplying the two arrays:')
print(np.multiply(arrOP1, arrOP2))

print('\nDividing the two arrays:')
print(np.divide(arrOP1, arrOP2))


First array:
[[0 1]
 [2 3]]

Second array:
[12 12]

Adding the two arrays:
[[12 13]
 [14 15]]

Subtracting the two arrays:
[[-12 -11]
 [-10  -9]]

Multiplying the two arrays:
[[ 0 12]
 [24 36]]

Dividing the two arrays:
[[0.         0.08333333]
 [0.16666667 0.25      ]]


## DataTypes:

In [39]:
#data type of an array containing numbers:
arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr3.dtype)

int32


In [40]:
#data type of an array containing strings:

arrs = np.array(['apple', 'banana', 'cherry'])

print(arrs.dtype)


<U6


### Creating Arrays With a Defined Data Type:

In [41]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [42]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# Array Manipulation

### Copy and View in Array: 

In [43]:
# COPY Array
arrC=np.array([1,2,3,4,5,6,7])
x=arrC.copy()
arrC[0]=14
print("Original Array with updated element:",arrC)
print("Copied array:",x)                          # In Copy, array is not affected by changes 

Original Array with updated element: [14  2  3  4  5  6  7]
Copied array: [1 2 3 4 5 6 7]


In [44]:
# VIEW Array

arrV=np.array([1,2,3,4,5,6,7])
x=arrV.view()
arrV[0]=14
print("Original Array with updated element:",arrV)
print("Copied array:",x)                            #In view arrays are affected by changes

Original Array with updated element: [14  2  3  4  5  6  7]
Copied array: [14  2  3  4  5  6  7]


### Using np.empty_like() function
This function returns a new array with the same shape and type as a given array.

In [45]:
ary = np.array([13, 99, 100, 34, 65, 11,66, 81, 632, 44])

print("Original array: ",ary)

copy = np.empty_like(ary)

copy[:] = ary

print("\nCopy of the given array: ",copy)


Original array:  [ 13  99 100  34  65  11  66  81 632  44]

Copy of the given array:  [ 13  99 100  34  65  11  66  81 632  44]


## Numpy Array Shape & Reshape

### shape()

Shape of an Array
The shape of an array is the number of elements in each dimension.



In [46]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) 

(2, 4)


In [47]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [48]:
# Integers at every index tells about the number of elements the corresponding dimension has.

# In the example above at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.

### Reshape
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 4)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)     # 2 arrays contain 3 arrays and that 3 arrays contains 2 elements each

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Joining Array

### np.concatenate()

In [51]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [52]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


[[1 2 5 6]
 [3 4 7 8]]


In [53]:
arr1=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

arr2=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]


### Joining Arrays Using Stack Functions
### stack():

In [54]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


### numpy.hstack() :
numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.

In [55]:
# hstack() function

in_arr1 = np.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

in_arr2 = np.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays horizontally
out_arr = np.hstack((in_arr1, in_arr2))
print ("Output horizontally stacked array:\n ", out_arr)


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


### numpy.vstack() function:
numpy.vstack() function is used to stack the sequence of input arrays vertically (i.e. row wise) to make a single array.

In [56]:
# vstack() function

# input array
in_arr1 = np.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

in_arr2 = np.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays vertically
out_arr = np.vstack((in_arr1, in_arr2))
print ("Output vertically stacked array:\n ", out_arr)


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


## numpy.dstack():
To get the combined array in a stack index by index.

In [57]:
gfg1 = np.array([1, 2, 3])
gfg2 = np.array([4, 5, 6])

# using numpy.dstack() method
print(np.dstack((gfg1, gfg2)))


[[[1 4]
  [2 5]
  [3 6]]]


## np.block()

In [58]:
block_1 = np.array([[1, 1], [1, 1]])
block_2 = np.array([[2, 2, 2], [2, 2, 2]])
block_3 = np.array([[3, 3], [3, 3], [3, 3]])
block_4 = np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4]])

block_new = np.block([
    [block_1, block_2],
    [block_3, block_4]
])

print(block_new)


[[1 1 2 2 2]
 [1 1 2 2 2]
 [3 3 4 4 4]
 [3 3 4 4 4]
 [3 3 4 4 4]]


## numpy.nditer()
To combine 1-D and 2-D arrays and display their elements.

In [59]:
num_1d = np.arange(5)
print("One dimensional array:")
print(num_1d)

num_2d = np.arange(10).reshape(2,5)
print("\nTwo dimensional array:")
print(num_2d)

# Combine 1-D and 2-D arrays and display
# their elements using numpy.nditer()
for a, b in np.nditer([num_1d, num_2d]):
	print("%d:%d" % (a, b),)


One dimensional array:
[0 1 2 3 4]

Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


# Array Split
Array splitting can be vertical, horizontal, or depth-wise. We can use functions hsplit(), vsplit() and dsplit() respectively 
for the same .We can split arrays into arrays of the same shape by indicating the position after which the split should occur.

In [60]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)    #here, arr is splited in 2 sub arrays

print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [61]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


### hsplit():

In [63]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.hsplit(arr, 2)

print(newarr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


### vsplit():

In [64]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.vsplit(arr, 2)

print(newarr)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])


[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]


[[1 2]
 [3 4]
 [5 6]]


[[ 7  8]
 [ 9 10]
 [11 12]]


### numpy.dsplit()- Depth-wise splitting: 
It Split the array into multiple sub-arrays along the 3rd axis (depth).
numpy.dsplit(ary, indices_or_sections)

In [65]:
arr = np.arange(27).reshape(3, 3, 3)

newarr = np.dsplit(arr, 3)

print(newarr)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])


[array([[[ 0],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]],

       [[18],
        [21],
        [24]]]), array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]],

       [[19],
        [22],
        [25]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]],

       [[20],
        [23],
        [26]]])]


[[[ 0]
  [ 3]
  [ 6]]

 [[ 9]
  [12]
  [15]]

 [[18]
  [21]
  [24]]]


[[[ 1]
  [ 4]
  [ 7]]

 [[10]
  [13]
  [16]]

 [[19]
  [22]
  [25]]]


# Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

## where():
 It returns the indices of elements in an input array where the given condition is satisfied.

In [66]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)        # Return element position index where it is present 
                              # here element 4 is present at index 3,5,6


print(x)

(array([3, 5, 6], dtype=int64),)


## numpy.searchsorted():
It performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [67]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 10)

print(x)                     # Return index where the element should added to remain sorted array

4


In [68]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x) 

2


In [69]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


# Sorting Arrays:
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

## sort()

In [70]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [71]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [72]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [73]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [1]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

SyntaxError: invalid syntax (Temp/ipykernel_12656/242419622.py, line 11)

### Creating Filter Directly From Array

In [75]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
